#!/bin/bash
# =============================================================================
# Ctags Configuration Verification Script
# =============================================================================
# This script runs ctags on the test files using ONLY the repo's .ctags config
# (ignoring ~/.ctags) and displays the results for verification.

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"
TEST_DIR="$SCRIPT_DIR"
CTAGS_CONFIG="$REPO_ROOT/.ctags"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Ctags Configuration Verification${NC}"
echo -e "${BLUE}========================================${NC}"
echo

# Check if ctags is installed
if ! command -v ctags &> /dev/null; then
    echo -e "${RED}Error: ctags is not installed${NC}"
    echo "Please install Exuberant Ctags or Universal Ctags"
    exit 1
fi

# Display ctags version
echo -e "${YELLOW}Ctags version:${NC}"
ctags --version 2>/dev/null | head -n 1
echo

# Verify config file exists
if [ ! -f "$CTAGS_CONFIG" ]; then
    echo -e "${RED}Error: Config file not found: $CTAGS_CONFIG${NC}"
    exit 1
fi

echo -e "${YELLOW}Using config file:${NC} $CTAGS_CONFIG"
echo -e "${YELLOW}Ignoring:${NC} ~/.ctags (using --options=NONE)"
echo

# Create a temporary tags file
TAGS_FILE=$(mktemp)
trap "rm -f $TAGS_FILE" EXIT

# Run ctags with --options=NONE to ignore all default config files,
# then load only our specific config
echo -e "${YELLOW}Running ctags on test files...${NC}"
ctags --options=NONE --options="$CTAGS_CONFIG" \
    -f "$TAGS_FILE" \
    "$TEST_DIR"/*.ts \
    "$TEST_DIR"/*.js \
    "$TEST_DIR"/*.cjs \
    "$TEST_DIR"/*.mjs \
    "$TEST_DIR"/*.vue \
    2>&1 || true
echo

# Function to display tags for a file
show_tags_for_file() {
    local file="$1"
    local basename=$(basename "$file")
    local abspath=$(realpath "$file" 2>/dev/null || echo "$file")

    echo -e "${GREEN}=== $basename ===${NC}"

    # Extract tags for this file, showing tag name, kind, and line number
    local tags=$(grep "	$abspath	" "$TAGS_FILE" 2>/dev/null || true)

    if [ -z "$tags" ]; then
        echo "  (no tags found)"
    else
        echo "$tags" | awk -F'\t' '{
            # Extract the kind from the 4th field
            kind = $4
            gsub(/;.*/, "", kind)
            # Print formatted output
            printf "  %-40s [%s] line %s\n", $1, kind, $3
        }' | sort -t'[' -k2 -k1
    fi

    echo
}

# Display tags for each test file
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Tags Generated by File${NC}"
echo -e "${BLUE}========================================${NC}"
echo

for file in "$TEST_DIR"/*.ts "$TEST_DIR"/*.js "$TEST_DIR"/*.cjs "$TEST_DIR"/*.mjs "$TEST_DIR"/*.vue; do
    if [ -f "$file" ]; then
        show_tags_for_file "$file"
    fi
done

# Summary statistics
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Summary Statistics${NC}"
echo -e "${BLUE}========================================${NC}"
echo

echo -e "${YELLOW}Total tags by kind:${NC}"
awk -F'\t' '{print $4}' "$TAGS_FILE" 2>/dev/null | \
    sed 's/;.*//' | \
    sort | uniq -c | sort -rn | \
    awk '{
        kind = $2
        count = $1
        if (kind == "c") desc = "classes"
        else if (kind == "f") desc = "functions"
        else if (kind == "m") desc = "methods"
        else if (kind == "p") desc = "properties"
        else if (kind == "v") desc = "variables"
        else if (kind == "i") desc = "interfaces"
        else if (kind == "t") desc = "types"
        else if (kind == "e") desc = "enums"
        else if (kind == "n") desc = "modules/namespaces"
        else desc = kind
        printf "  %-5s %-20s %d\n", kind, desc, count
    }'
echo

echo -e "${YELLOW}Tags per file:${NC}"
for file in "$TEST_DIR"/*.ts "$TEST_DIR"/*.js "$TEST_DIR"/*.cjs "$TEST_DIR"/*.mjs "$TEST_DIR"/*.vue; do
    if [ -f "$file" ]; then
        basename=$(basename "$file")
        abspath=$(realpath "$file" 2>/dev/null || echo "$file")
        count=$(grep -c "	$abspath	" "$TAGS_FILE" 2>/dev/null || echo "0")
        printf "  %-30s %s tags\n" "$basename" "$count"
    fi
done
echo

total=$(wc -l < "$TAGS_FILE" 2>/dev/null || echo "0")
echo -e "${GREEN}Total tags generated: $total${NC}"
echo

# Show what patterns SHOULD be found but might be missing
echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Expected Pattern Coverage${NC}"
echo -e "${BLUE}========================================${NC}"
echo
echo -e "${CYAN}The test files contain these common patterns:${NC}"
echo "  - Classes (regular, exported, default, abstract)"
echo "  - Interfaces"
echo "  - Type aliases"
echo "  - Enums (regular, string, const)"
echo "  - Functions (regular, async, generator, exported)"
echo "  - Methods (regular, async, static, private, getters/setters)"
echo "  - Properties (regular, static, private #fields)"
echo "  - Variables (const, let, var, arrow functions)"
echo "  - Namespaces/Modules"
echo
echo -e "${CYAN}Check the output above to verify all patterns are captured.${NC}"
echo

# Optional: Show the raw tags file
if [ "$1" == "--raw" ]; then
    echo -e "${BLUE}========================================${NC}"
    echo -e "${BLUE}Raw Tags File Content${NC}"
    echo -e "${BLUE}========================================${NC}"
    echo
    cat "$TAGS_FILE"
fi

echo -e "${GREEN}Verification complete!${NC}"
